# Generated by Django 6.0.7 on 2026-08-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=200, verbose_name='मन्त्रालयको नाम')),
                ('department_name', models.CharField(max_length=200, verbose_name='विभाग वा निर्देशनालय')),
                ('office_name', models.CharField(max_length=200, verbose_name='कार्यालयको नाम')),
                ('office_address', models.CharField(max_length=200, verbose_name='कार्यालयको ठेगाना')),
                ('office_code', models.CharField(max_length=50, verbose_name='कार्यालय कोड')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='नाम थर')),
                ('designation', models.CharField(max_length=100, verbose_name='पद')),
                ('person_type', models.CharField(choices=[('internal', 'कार्यालयको कर्मचारी'), ('external', 'बाहिरको कर्मचारी वा व्यक्ति')], default='internal', max_length=20, verbose_name='कर्मचारीको प्रकार')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='कर्मचारी संकेत नं')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='भ्रमण आदेश नं.')),
                ('destination', models.CharField(max_length=200, verbose_name='भ्रमण गर्ने स्थान')),
                ('purpose', models.TextField(verbose_name='भ्रमणको उद्देश्य')),
                ('start_date', models.DateField(verbose_name='सुरु मिति')),
                ('end_date', models.DateField(verbose_name='सकिने मिति')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='पेस्की रकम (रु)')),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='पेश गरेको जम्मा बिल (रु)')),
                ('is_report_submitted', models.BooleanField(default=False, verbose_name='भ्रमण प्रतिवेदन बुझायो?')),
                ('clearance_requested', models.BooleanField(default=False, verbose_name='भुक्तानी/फर्छ्यौटको निवेदन दियो?')),
                ('status', models.CharField(choices=[('1_order', '१. भ्रमण आदेश जारी'), ('2_advance', '२. पेस्की लिएको अवस्था'), ('3_report_bill', '३. प्रतिवेदन र बिल पेश भयो'), ('4_cleared', '४. भुक्तानी/फर्छ्यौट सम्पन्न (खाता बन्द)')], default='1_order', max_length=30, verbose_name='हालको अवस्था')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='कैफियत (थप जानकारी)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.person', verbose_name='भ्रमण गर्ने व्यक्ति')),
            ],
        ),
    ]
