# Generated by Django 6.0.7 on 2026-08-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeprofile',
            name='province_government',
            field=models.CharField(default='कोशी प्रदेश सरकार', max_length=200, verbose_name='प्रदेश/नेपाल सरकार'),
        ),
    ]
