# Generated by Django 6.0.7 on 2026-08-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_officeprofile_province_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('permanent', 'स्थायी'), ('contract', 'करार'), ('daily_wage', 'ज्यालादारी')], default='permanent', max_length=20, verbose_name='कर्मचारीको प्रकार'),
        ),
    ]
