# Generated by Django 6.0.7 on 2026-08-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_person_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrecord',
            name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='clearance_requested',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='is_report_submitted',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='remarks',
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='applicant_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='भ्रमण गर्ने पदाधिकारीको मिति'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='approver_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='स्वीकृत मिति'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='approver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='भ्रमण स्वीकृत गर्ने पदाधिकारी'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='attendance_record_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='हाजिरी खातामा जनाएको मिति'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मिति (आदेश नम्बरको तल)'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='भ्रमण सम्बन्धी अन्य आवश्यक विवरण'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='program_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='खर्च जनाउने कार्यक्रम/आयोजनाको नाम'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='recommender_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='सिफारिस मिति'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='recommender_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='सिफारिस गर्ने पदाधिकारी'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='transport_mode',
            field=models.CharField(choices=[('office', 'कार्यालयको'), ('public', 'सार्वजनिक'), ('rented', 'भाडाको')], default='public', max_length=20, verbose_name='भ्रमण गर्ने साधन'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='travel_type',
            field=models.CharField(choices=[('national', 'राष्ट्रिय भ्रमण आदेश'), ('international', 'अन्तर्राष्ट्रिय भ्रमण आदेश')], default='national', max_length=20, verbose_name='भ्रमणको प्रकार'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='working_office',
            field=models.CharField(default='भेटेरिनरी अस्पताल तथा पशु सेवा विज्ञ केन्द्र, झापा', max_length=200, verbose_name='कार्यरत कार्यालय'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='भ्रमणका निमित्त माग गरेको पेस्की (रु)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='end_date',
            field=models.CharField(max_length=20, verbose_name='भ्रमण सकिने मिति (सम्म)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.person', verbose_name='भ्रमण गर्ने पदाधिकारी'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='start_date',
            field=models.CharField(max_length=20, verbose_name='भ्रमण सुरु मिति (देखि)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='status',
            field=models.CharField(default='1_order', max_length=30, verbose_name='हालको अवस्था'),
        ),
    ]
