# Generated by Django 6.0.7 on 2026-08-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_travelrecord_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecord',
            name='applicant_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मिति (भ्रमण गर्ने पदाधिकारी)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='approver_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मिति (स्वीकृत गर्ने)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='end_date',
            field=models.CharField(max_length=20, verbose_name='मिति (सम्म)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मिति'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='recommender_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मिति (सिफारिस गर्ने)'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='start_date',
            field=models.CharField(max_length=20, verbose_name='भ्रमण गर्ने अवधि: मिति (देखि)'),
        ),
    ]
