# Generated by Django 6.0.7 on 2026-08-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_travelrecord_applicant_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrecord',
            name='approver_name',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='recommender_name',
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travels', to='travel.person', verbose_name='भ्रमण स्वीकृत गर्ने पदाधिकारी'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_travels', to='travel.person', verbose_name='सिफारिस गर्ने पदाधिकारी'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='travel.person', verbose_name='भ्रमण गर्ने पदाधिकारी'),
        ),
    ]
