# Generated by Django 6.0.7 on 2026-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_travelrecord_approver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='तह / श्रेणी'),
        ),
        migrations.AddField(
            model_name='person',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='कर्मचारीको स्थायी ठेगाना'),
        ),
    ]
