# Generated by Django 6.0.7 on 2026-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_person_level_person_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(blank=True, choices=[('unranked', 'ह. स. चा. तथा श्रेणीबिहीन'), ('4th', 'चौथो'), ('5th', 'पाँचौं'), ('6th', 'छैटौं'), ('7th', 'सातौं'), ('8th', 'आठौं'), ('9th', 'नवौं'), ('10th', 'दशौं'), ('11th', 'एघारौ'), ('12th', 'बार्हौं')], max_length=50, null=True, verbose_name='तह / श्रेणी'),
        ),
    ]
