# Generated by Django 6.0.7 on 2026-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_person_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='मोबाइल नम्बर'),
        ),
    ]
