# Generated by Django 6.0.7 on 2026-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_person_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='कर्मचारीको नाम')),
                ('designation', models.CharField(max_length=100, verbose_name='पद')),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='संकेत नं')),
                ('purpose', models.CharField(max_length=255, verbose_name='भ्रमणको उद्देश्य')),
                ('address', models.CharField(max_length=255, verbose_name='स्थायी ठेगाना')),
                ('order_no', models.CharField(max_length=50, verbose_name='भ्रमण आदेश सि नं.')),
                ('total_transport', models.IntegerField(default=0, verbose_name='१. भ्रमण/यातायात खर्च')),
                ('total_daily_allowance', models.IntegerField(default=0, verbose_name='२. दैनिक भत्ता')),
                ('total_misc', models.IntegerField(default=0, verbose_name='४. फुटकर खर्च')),
                ('advance_taken', models.IntegerField(default=0, verbose_name='६. भ्रमण पेस्की')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='आदेश नं')),
                ('person', models.CharField(max_length=100, verbose_name='कर्मचारीको नाम')),
                ('destination', models.CharField(max_length=100, verbose_name='भ्रमण गर्ने स्थान')),
                ('purpose', models.CharField(max_length=255, verbose_name='भ्रमणको उद्देश्य')),
                ('start_date', models.CharField(max_length=50, verbose_name='शुरु मिति')),
                ('end_date', models.CharField(max_length=50, verbose_name='अन्त्य मिति')),
                ('advance_amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='पेस्की रकम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeProfile',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='recommender',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='TravelRecord',
        ),
    ]
