# Generated by Django 6.0.7 on 2026-08-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_travelbill_travelorder_delete_officeprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelbill',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='travelbill',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='travelbill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='travelbill',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='travelbill',
            name='purpose',
        ),
        migrations.AddField(
            model_name='travelbill',
            name='travel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.travelorder', verbose_name='भ्रमण आदेश छान्नुहोस्'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='address',
            field=models.CharField(max_length=255, verbose_name='कर्मचारीको स्थायी ठेगाना'),
        ),
    ]
