# Generated by Django 6.0.7 on 2026-08-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_travelbill_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='कर्मचारीको नामथर')),
                ('code_no', models.CharField(max_length=50, unique=True, verbose_name='कर्मचारी संकेत नं')),
                ('designation', models.CharField(max_length=100, verbose_name='पद')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='तह / श्रेणी')),
                ('office', models.CharField(default='भेटेरिनरी अस्पताल तथा पशु सेवा विज्ञ केन्द्र, भद्रपुर झापा', max_length=255, verbose_name='कार्यालय')),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='स्थायी ठेगाना')),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='सम्पर्क नं')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय स्थिति')),
            ],
            options={
                'verbose_name': 'कर्मचारी विवरण',
                'verbose_name_plural': 'कर्मचारीहरूको सूची',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='travelbill',
            options={'ordering': ['-id'], 'verbose_name': 'दैनिक तथा भ्रमण खर्चको बिल (म.ले.प. २२४)', 'verbose_name_plural': 'दैनिक तथा भ्रमण खर्चका बिलहरू'},
        ),
        migrations.AlterModelOptions(
            name='travelorder',
            options={'ordering': ['-id'], 'verbose_name': 'राष्ट्रिय भ्रमण आदेश (म.ले.प. २२३)', 'verbose_name_plural': 'राष्ट्रिय भ्रमण आदेशहरू'},
        ),
        migrations.AddField(
            model_name='travelbill',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='खुद रकम अक्षरमा'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='bill_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='बिल पेश मिति'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='grand_total',
            field=models.IntegerField(default=0, verbose_name='५. कुल जम्मा (रु.)'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='net_payable',
            field=models.IntegerField(default=0, verbose_name='७. खुद भुक्तानी पाउने/बुझाउने रकम (रु.)'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='receipt_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='नत्थी रसिद/बिल संख्या'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='report_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='भ्रमण प्रतिवेदन दर्ता नं'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='admin_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='हाजिरी खातामा जनाएको मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='advance_words',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='पेस्की रकम अक्षरमा'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='code_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='कर्मचारी संकेत नं'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='पद'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='fiscal_year',
            field=models.CharField(default='२०८२/८३', max_length=20, verbose_name='आर्थिक वर्ष'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='office',
            field=models.CharField(default='भेटेरिनरी अस्पताल तथा पशु सेवा विज्ञ केन्द्र, भद्रपुर झापा', max_length=255, verbose_name='कार्यालय'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='order_date',
            field=models.CharField(default='२०८२/०४/२०', max_length=50, verbose_name='आदेश मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='भ्रमण सम्बन्धी अन्य आवश्यक विवरण'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='खर्च जनाउने कार्यक्रम/आयोजनाको नाम'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='अद्यावधिक मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='vehicle_office',
            field=models.BooleanField(default=False, verbose_name='साधन: कार्यालयको'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='vehicle_public',
            field=models.BooleanField(default=True, verbose_name='साधन: सार्वजनिक'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='vehicle_rent',
            field=models.BooleanField(default=False, verbose_name='साधन: भाडाको'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='कर्मचारीको स्थायी ठेगाना'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='advance_taken',
            field=models.IntegerField(default=0, verbose_name='६. भ्रमण पेस्की (रु.)'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='total_daily_allowance',
            field=models.IntegerField(default=0, verbose_name='२. दैनिक भत्ता (रु.)'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='total_misc',
            field=models.IntegerField(default=0, verbose_name='४. फुटकर खर्च (रु.)'),
        ),
        migrations.AlterField(
            model_name='travelbill',
            name='total_transport',
            field=models.IntegerField(default=0, verbose_name='१. भ्रमण/यातायात खर्च (रु.)'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='advance_amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='पेस्की रकम (रु.)'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='भ्रमण गर्ने स्थान'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='end_date',
            field=models.CharField(max_length=50, verbose_name='भ्रमण अवधि अन्त्य मिति'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='person',
            field=models.CharField(max_length=100, verbose_name='कर्मचारीको नामथर'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='purpose',
            field=models.CharField(default='तोकिएको सरकारी कामकाज', max_length=255, verbose_name='भ्रमणको उद्देश्य'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='start_date',
            field=models.CharField(max_length=50, verbose_name='भ्रमण अवधि शुरु मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.employee', verbose_name='कर्मचारी छान्नुहोस् (Employee)'),
        ),
        migrations.CreateModel(
            name='TravelBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.CharField(default='झापा', max_length=100, verbose_name='प्रस्थान स्थान (महल १)')),
                ('departure_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='प्रस्थान मिति (महल २)')),
                ('departure_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='प्रस्थान समय')),
                ('arrival_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='आगमन स्थान (महल ३)')),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='आगमन मिति (महल ४)')),
                ('arrival_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='आगमन समय')),
                ('transport_medium', models.CharField(blank=True, default='सार्वजनिक सवारी', max_length=100, null=True, verbose_name='भ्रमणको साधन (महल ५)')),
                ('transport_fare', models.IntegerField(default=0, verbose_name='यातायात खर्च रू (महल ६)')),
                ('daily_allowance_days', models.FloatField(default=1.0, verbose_name='दैनिक भत्ता दिन (महल ७)')),
                ('daily_allowance_rate', models.IntegerField(default=0, verbose_name='दैनिक भत्ता दर (महल ८)')),
                ('daily_allowance_total', models.IntegerField(default=0, verbose_name='दैनिक भत्ता जम्मा रू (महल ९)')),
                ('misc_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='फुटकर खर्च विवरण (महल १०)')),
                ('misc_amount', models.IntegerField(default=0, verbose_name='फुटकर खर्च जम्मा रू (महल ११)')),
                ('row_total', models.IntegerField(default=0, verbose_name='कुल जम्मा रू (महल १२)')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='कैफियत (महल १३)')),
                ('travel_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.travelbill', verbose_name='बिल')),
            ],
            options={
                'verbose_name': 'भ्रमण बिल खर्च पंक्ति (महल १ देखि १३)',
                'verbose_name_plural': 'भ्रमण बिल खर्च पंक्तिहरू',
            },
        ),
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(default='२०८२/०४/२५', max_length=50, verbose_name='प्रतिवेदन पेश गरेको मिति')),
                ('report_reg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='प्रतिवेदन दर्ता नं')),
                ('key_activities', models.TextField(verbose_name='१. सम्पादित मुख्य कार्यहरू (Key Activities)')),
                ('achievements', models.TextField(verbose_name='२. हासिल भएका मुख्य उपलब्धिहरू (Achievements)')),
                ('challenges', models.TextField(blank=True, null=True, verbose_name='३. देखिएका समस्या तथा चुनौतीहरू (Challenges)')),
                ('recommendations', models.TextField(verbose_name='४. निष्कर्ष तथा सुझावहरू (Recommendations)')),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='प्रतिवेदन पेश गर्ने कर्मचारीको नाम')),
                ('submitted_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='पद')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('travel_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='travel.travelorder', verbose_name='भ्रमण आदेश छान्नुहोस्')),
            ],
            options={
                'verbose_name': 'भ्रमण सम्पन्न प्रतिवेदन (Travel Completion Report)',
                'verbose_name_plural': 'भ्रमण सम्पन्न प्रतिवेदनहरू',
                'ordering': ['-id'],
            },
        ),
    ]
