# Generated by Django 6.0.7 on 2026-08-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_employee_alter_travelbill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='कार्यालयको नाम (Office Name)')),
                ('parent_body_1', models.CharField(blank=True, default='कोशी प्रदेश सरकार', max_length=255, null=True, verbose_name='प्रदेश / संघीय सरकार (Level 1)')),
                ('parent_body_2', models.CharField(blank=True, default='उद्योग, कृषि तथा सहकारी मन्त्रालय', max_length=255, null=True, verbose_name='मन्त्रालय (Ministry - Level 2)')),
                ('parent_body_3', models.CharField(blank=True, default='पशुपन्छी तथा मत्स्य विकास निर्देशनालय', max_length=255, null=True, verbose_name='विभाग / निर्देशनालय (Department/Directorate - Level 3)')),
                ('office_code', models.CharField(blank=True, default='३१२०२१२०११', max_length=50, null=True, verbose_name='कार्यालय कोड नं. (Office Code)')),
                ('location', models.CharField(blank=True, default='भद्रपुर, झापा', max_length=255, null=True, verbose_name='ठेगाना / जिल्ला (Location)')),
                ('head_title', models.CharField(default='कार्यालय प्रमुख', help_text='जस्तै: कार्यालय प्रमुख, प्रमुख प्रशासकीय अधिकृत, आयोजना प्रमुख, महानिर्देशक', max_length=100, verbose_name='कार्यालय प्रमुखको पद (Head Designation)')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='फोन नं.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='इमेल')),
                ('is_default', models.BooleanField(default=False, verbose_name='सक्रिय / पूर्वनिर्धारित कार्यालय (Active/Default Office)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'verbose_name': 'कार्यालय (Office)',
                'verbose_name_plural': 'कार्यालयहरूको व्यवस्थापन (Offices)',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(default='भेटेरिनरी अस्पताल तथा पशु सेवा विज्ञ केन्द्र, भद्रपुर झापा', max_length=255, verbose_name='कार्यालयको नाम'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.office', verbose_name='सम्बन्धित कार्यालय (Office)'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='office_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.office', verbose_name='सम्बन्धित कार्यालय (Office)'),
        ),
    ]
