# Generated by Django 6.0.7 on 2026-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_office_alter_employee_office_employee_office_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='approver_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='भ्रमण स्वीकृत गर्ने पदाधिकारीको मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='recommender_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='सिफारिस गर्ने पदाधिकारीको मिति'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='traveller_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='भ्रमण गर्ने पदाधिकारीको मिति'),
        ),
    ]
