# Generated by Django 6.0.7 on 2026-08-07 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_travelorder_approver_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbill',
            name='travel_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='travel.travelorder', verbose_name='भ्रमण आदेश छान्नुहोस्'),
        ),
    ]
