# Generated by Django 6.0.7 on 2026-08-07 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_travelbill_travel_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='युजर खाता (User Account)'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_travel_orders', to=settings.AUTH_USER_MODEL, verbose_name='सिर्जना गर्ने युजर (Created By)'),
        ),
    ]
