# Generated by Django 6.0.7 on 2026-08-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_employee_user_travelorder_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='आदेश नं'),
        ),
        migrations.CreateModel(
            name='FiscalYearSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=20, verbose_name='आर्थिक वर्ष')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='पछिल्लो आदेश नं.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.office', verbose_name='कार्यालय')),
            ],
            options={
                'verbose_name': 'आर्थिक वर्ष आदेश क्रम संख्या (Sequence)',
                'verbose_name_plural': 'आदेश क्रम संख्याहरू',
                'unique_together': {('fiscal_year', 'office_ref')},
            },
        ),
    ]
