# Generated by Django 6.0.7 on 2026-08-08 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_travelorder_order_number_fiscalyearsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_allowance_rate',
            field=models.PositiveIntegerField(default=1600, help_text='कर्मचारीको तह अनुसार तोकिएको प्रतिदिन भ्रमण भत्ता दर', verbose_name='दैनिक भत्ता दर (रु.)'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='external_agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='बाह्य निकायको नाम'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='paying_agency_type',
            field=models.CharField(choices=[('INTERNAL', 'यसै कार्यालयको बजेटबाट भुक्तानी'), ('EXTERNAL', 'अन्य सरकारी निकाय / बाह्य स्रोतबाट भुक्तानी')], db_index=True, default='INTERNAL', max_length=20, verbose_name='भुक्तानी गर्ने निकाय'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travel_orders', to=settings.AUTH_USER_MODEL, verbose_name='स्वीकृत गर्ने'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_travel_orders', to=settings.AUTH_USER_MODEL, verbose_name='सिफारिस गर्ने'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'पेश भएको (विचाराधीन)'), ('RECOMMENDED', 'सिफारिस गरिएको'), ('APPROVED', 'स्वीकृत'), ('FINANCE_CLEARED', 'लेखाबाट फछ्र्यौट भएको'), ('REGISTERED', 'दर्ता भई अन्तिम भएको'), ('REJECTED', 'अस्वीकृत / फिर्ता')], db_index=True, default='REGISTERED', max_length=20, verbose_name='आदेश स्थिति'),
        ),
    ]
