# Generated by Django 6.1 on 2026-08-12 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_employee_daily_allowance_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL, verbose_name='व्यवस्थापन गर्ने युजर (Managed By)'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='fiscal_year',
            field=models.CharField(default='२०८३/८४', max_length=20, verbose_name='आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='order_date',
            field=models.CharField(default='२०८३/०४/२५', max_length=50, verbose_name='आदेश मिति'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'मस्यौदा'), ('PENDING', 'पेश भएको (विचाराधीन)'), ('RECOMMENDED', 'सिफारिस गरिएको'), ('APPROVED', 'स्वीकृत'), ('FINANCE_CLEARED', 'लेखाबाट फछ्र्यौट भएको'), ('REGISTERED', 'दर्ता भई अन्तिम भएको'), ('ATTENDANCE_RECORDED', 'हाजिरी खातामा चढाइएको'), ('REJECTED', 'अस्वीकृत / फिर्ता')], db_index=True, default='DRAFT', max_length=20, verbose_name='आदेश स्थिति'),
        ),
        migrations.AlterField(
            model_name='travelreport',
            name='report_date',
            field=models.CharField(default='२०८३/०४/२५', max_length=50, verbose_name='प्रतिवेदन पेश गरेको मिति'),
        ),
    ]
