# Generated by Django 6.1 on 2026-08-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_employee_managed_by_alter_travelorder_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_paying_agency',
            field=models.BooleanField(default=False, verbose_name='अन्य प्रयोजन (Paying Agency)'),
        ),
        migrations.AddField(
            model_name='travelbill',
            name='paying_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_bills', to='travel.office', verbose_name='भुक्तानी गर्ने कार्यालय'),
        ),
    ]
